//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace stranger80 { namespace SoViAgent {

ref class SoViAgentSignals;

public interface class ISoViAgentSignals
{
    event Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentHeatPointCompletedReceivedEventArgs^>^ HeatPointCompletedReceived;
    event Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentDeviceErrorOccurredReceivedEventArgs^>^ DeviceErrorOccurredReceived;
};

public ref class SoViAgentSignals sealed : [Windows::Foundation::Metadata::Default] ISoViAgentSignals
{
public:
    // Calling this method will send the HeatPointCompleted signal to every member of the session.
    void HeatPointCompleted(_In_ bool interfaceMemberIsHeatPatternComplete);

    // This event fires whenever the HeatPointCompleted signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentHeatPointCompletedReceivedEventArgs^>^ HeatPointCompletedReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentHeatPointCompletedReceivedEventArgs^>^ handler) 
        { 
            return _HeatPointCompletedReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SoViAgentSignals^>(sender), safe_cast<SoViAgentHeatPointCompletedReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _HeatPointCompletedReceived -= token; 
        } 
    internal: 
        void raise(SoViAgentSignals^ sender, SoViAgentHeatPointCompletedReceivedEventArgs^ args) 
        { 
            _HeatPointCompletedReceived(sender, args);
        } 
    }

    // Calling this method will send the DeviceErrorOccurred signal to every member of the session.
    void DeviceErrorOccurred(_In_ SoViAgentErrorDescription^ interfaceMemberErrorDescription);

    // This event fires whenever the DeviceErrorOccurred signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentDeviceErrorOccurredReceivedEventArgs^>^ DeviceErrorOccurredReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SoViAgentSignals^, SoViAgentDeviceErrorOccurredReceivedEventArgs^>^ handler) 
        { 
            return _DeviceErrorOccurredReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SoViAgentSignals^>(sender), safe_cast<SoViAgentDeviceErrorOccurredReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _DeviceErrorOccurredReceived -= token; 
        } 
    internal: 
        void raise(SoViAgentSignals^ sender, SoViAgentDeviceErrorOccurredReceivedEventArgs^ args) 
        { 
            _DeviceErrorOccurredReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallHeatPointCompletedReceived(_In_ SoViAgentSignals^ sender, _In_ SoViAgentHeatPointCompletedReceivedEventArgs^ args);
    void CallDeviceErrorOccurredReceived(_In_ SoViAgentSignals^ sender, _In_ SoViAgentDeviceErrorOccurredReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _HeatPointCompletedReceived;
    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _DeviceErrorOccurredReceived;

    alljoyn_interfacedescription_member m_memberHeatPointCompleted;
    alljoyn_interfacedescription_member m_memberDeviceErrorOccurred;
};

} } } 
