//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace stranger80 { namespace SoViAgent {

public ref class SoViAgentHeatPointArrayItem sealed
{
public:
    property double Value1
    {
        double get() { return m_value1; }
        void set(double value) { m_value1 = value; }
    }
     
    property int32 Value2
    {
        int32 get() { return m_value2; }
        void set(int32 value) { m_value2 = value; }
    }
     
private:
    double m_value1;
    int32 m_value2;
};

public ref class SoViAgentSuccessItem sealed
{
public:
    property uint32 Value1
    {
        uint32 get() { return m_value1; }
        void set(uint32 value) { m_value1 = value; }
    }
     
    property double Value2
    {
        double get() { return m_value2; }
        void set(double value) { m_value2 = value; }
    }
     
    property byte Value3
    {
        byte get() { return m_value3; }
        void set(byte value) { m_value3 = value; }
    }
     
    property byte Value4
    {
        byte get() { return m_value4; }
        void set(byte value) { m_value4 = value; }
    }
     
private:
    uint32 m_value1;
    double m_value2;
    byte m_value3;
    byte m_value4;
};

public ref class SoViAgentErrorDescription sealed
{
public:
    property int32 Value1
    {
        int32 get() { return m_value1; }
        void set(int32 value) { m_value1 = value; }
    }
     
    property Platform::String^ Value2
    {
        Platform::String^ get() { return m_value2; }
        void set(Platform::String^ value) { m_value2 = value; }
    }
     
private:
    int32 m_value1;
    Platform::String^ m_value2;
};

public ref class AllJoynMessageArgStructure sealed : Windows::Foundation::Collections::IVector<Platform::Object^>
{
public:
    AllJoynMessageArgStructure()
    {
        m_vector = ref new Platform::Collections::Vector<Platform::Object^>();
    }

    virtual Windows::Foundation::Collections::IIterator<Platform::Object^>^ First()
    {
        return m_vector->First();
    }

    virtual Platform::Object^ GetAt(unsigned int index)
    {
        return m_vector->GetAt(index);
    }

    virtual property unsigned int Size {
        virtual unsigned int get()
        {
            return m_vector->Size;
        }
    }

    virtual bool IndexOf(Platform::Object^ value, unsigned int * index)
    {
        return m_vector->IndexOf(value, index);
    }

    virtual unsigned int GetMany(unsigned int startIndex, Platform::WriteOnlyArray<Platform::Object^>^ items)
    {
        return m_vector->GetMany(startIndex, items);
    }

    virtual Windows::Foundation::Collections::IVectorView<Platform::Object^>^ GetView()
    {
        return m_vector->GetView();
    }

    virtual void SetAt(unsigned int index, Platform::Object^ item)
    {
        return m_vector->SetAt(index, item);
    }

    virtual void InsertAt(unsigned int index, Platform::Object^ item)
    {
        return m_vector->InsertAt(index, item);
    }

    virtual void Append(Platform::Object^ item)
    {
        return m_vector->Append(item);
    }

    virtual void RemoveAt(unsigned int index)
    {
        return m_vector->RemoveAt(index);
    }

    virtual void RemoveAtEnd()
    {
        return m_vector->RemoveAtEnd();
    }

    virtual void Clear()
    {
        return m_vector->Clear();
    }

    virtual void ReplaceAll(const Platform::Array<Platform::Object^>^ arr)
    {
        return m_vector->ReplaceAll(arr);
    }

private:
    Platform::Collections::Vector<Platform::Object^>^ m_vector;
};
} } } 

partial ref class TypeConversionHelpers
{
internal:
    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ org::stranger80::SoViAgent::SoViAgentHeatPointArrayItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new org::stranger80::SoViAgent::SoViAgentHeatPointArrayItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(**)", &argument1, &argument2));

        double value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "d", &value1));
        (*value)->Value1 = value1;
        int32 value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "i", &value2));
        (*value)->Value2 = value2;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ org::stranger80::SoViAgent::SoViAgentHeatPointArrayItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "d", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "i", value->Value2));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(**)", argument1, argument2));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ org::stranger80::SoViAgent::SoViAgentSuccessItem^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new org::stranger80::SoViAgent::SoViAgentSuccessItem();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        alljoyn_msgarg argument3;
        alljoyn_msgarg argument4;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(****)", &argument1, &argument2, &argument3, &argument4));

        uint32 value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "u", &value1));
        (*value)->Value1 = value1;
        double value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "d", &value2));
        (*value)->Value2 = value2;
        byte value3;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument3, "y", &value3));
        (*value)->Value3 = value3;
        byte value4;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument4, "y", &value4));
        (*value)->Value4 = value4;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ org::stranger80::SoViAgent::SoViAgentSuccessItem^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "u", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "d", value->Value2));
        auto argument3 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument3, "y", value->Value3));
        auto argument4 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument4, "y", value->Value4));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(****)", argument1, argument2, argument3, argument4));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);
        alljoyn_msgarg_destroy(argument3);
        alljoyn_msgarg_destroy(argument4);

        return ER_OK;
    }

    static _Check_return_ int32 GetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _Out_ org::stranger80::SoViAgent::SoViAgentErrorDescription^* value)
    {
        UNREFERENCED_PARAMETER(signature);

        (*value) = ref new org::stranger80::SoViAgent::SoViAgentErrorDescription();

        alljoyn_msgarg argument1;
        alljoyn_msgarg argument2;
        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_get(argument, "(**)", &argument1, &argument2));

        int32 value1;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument1, "i", &value1));
        (*value)->Value1 = value1;
        Platform::String^ value2;
        RETURN_IF_QSTATUS_ERROR(GetAllJoynMessageArg(argument2, "s", &value2));
        (*value)->Value2 = value2;
        
        return ER_OK;
    }

    static _Check_return_ int32 SetAllJoynMessageArg(_In_ alljoyn_msgarg argument, _In_ PCSTR signature, _In_ org::stranger80::SoViAgent::SoViAgentErrorDescription^ value)
    {
        UNREFERENCED_PARAMETER(signature);

        auto argument1 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument1, "i", value->Value1));
        auto argument2 = alljoyn_msgarg_create();
        RETURN_IF_QSTATUS_ERROR(SetAllJoynMessageArg(argument2, "s", value->Value2));

        RETURN_IF_QSTATUS_ERROR(alljoyn_msgarg_set(argument, "(**)", argument1, argument2));
        alljoyn_msgarg_stabilize(argument);
        alljoyn_msgarg_destroy(argument1);
        alljoyn_msgarg_destroy(argument2);

        return ER_OK;
    }

};
